; G-Code generated by PrusaSlicer
; Layer height: 0.2mm
; Nozzle temperature: 210C
; Bed temperature: 60C
G28 ; Home all axes
G1 Z15.0 F6000 ; Move Z up
M104 S210 ; Set extruder temp
M140 S60 ; Set bed temp
M190 S60 ; Wait for bed temp
M109 S210 ; Wait for extruder temp
G21 ; Set units to millimeters
G90 ; Absolute positioning
M82 ; Absolute extrusion mode
G92 E0 ; Reset extruder
G1 F2400 E-0.8 ; Retract
G1 Z0.2 F3000 ; Move to layer height
G1 X10.0 Y10.0 F5000 ; Move to start position
G1 E0 F2400 ; Un-retract
