// Type contracts mirroring the Rust backend's serialized shapes. Generated by
// hand from src-tauri/src/{commands,ai,state,config}/**.rs — keep these in
// sync when backend structs change. A future improvement is to derive these
// via ts-rs or specta.

export interface FileInfo {
	path: string;
	name: string;
	size: number;
	mime_type?: string;
	is_directory: boolean;
	extension?: string;
	created_at?: number;
	modified_at?: number;
}

export interface FileAnalysis {
	path: string;
	category: string;
	tags: string[];
	summary: string;
	confidence: number;
	metadata?: Record<string, unknown>;
}

export interface AnalysisResult {
	success: boolean;
	analysis?: FileAnalysis;
	error?: string;
}

export interface OrganizationSuggestion {
	file_path: string;
	suggested_folder: string;
	confidence: number;
	reasoning?: string;
}

export interface ModelInfo {
	name: string;
	size: number;
	modified_at: string;
}

export interface OllamaStatus {
	// `isRunning` matches the mock shape; the Rust side serializes
	// `is_running` — see normalizeOllamaStatus in $lib/api/tauri.
	isRunning: boolean;
	is_installed?: boolean;
	version?: string | null;
	models: ModelInfo[] | string[];
	default_model?: string | null;
	host?: string;
}

export interface AppSettings {
	ai_provider: string;
	ollama_host: string;
	ollama_model: string;
	ollama_vision_model: string;
	ollama_embedding_model: string;

	watch_folders: boolean;
	watch_paths: string[];
	default_smart_folder_location: string;
	file_extensions_to_ignore: string[];
	max_file_size: number;

	max_concurrent_analysis: number;
	max_concurrent_operations: number;
	cache_size: number;
	enable_gpu: boolean;

	max_concurrent_reads: number;
	max_total_memory_mb: number;
	max_single_file_size_mb: number;
	max_directory_scan_depth: number;

	theme: 'auto' | 'light' | 'dark';
	language: string;
	show_notifications: boolean;
	notification_duration: number;

	enable_telemetry: boolean;
	enable_crash_reports: boolean;
	enable_analytics: boolean;

	confirm_before_delete: boolean;
	confirm_before_move: boolean;
	auto_analyze_on_add: boolean;
	preserve_file_timestamps: boolean;

	debug_mode: boolean;
	log_level: 'error' | 'warn' | 'info' | 'debug' | 'trace';
	history_retention: number;
	undo_history_size: number;
}

export interface SystemInfo {
	os: string;
	version: string;
	arch: string;
	cpu_cores?: number;
	total_memory?: number;
	available_memory?: number;
}

export interface SmartFolder {
	id: string;
	name: string;
	description?: string;
	target_path: string;
	rules: OrganizationRule[];
	created_at: string;
	updated_at: string;
	enabled: boolean;
}

export interface OrganizationRule {
	field: string;
	operator: string;
	value: string;
	action: { type: string; target_folder: string };
}

export interface HistoryEntry {
	id: string;
	operation_type: string;
	source?: string;
	destination?: string;
	timestamp: number;
}

export interface FirstRunStatus {
	is_first_run: boolean;
	setup_completed?: boolean;
}

export interface BatchOperationResult {
	successful: FileAnalysis[];
	failed: Array<{ path: string; error: string }>;
	total: number;
}

export interface SearchResult {
	path: string;
	name?: string;
	score: number;
	snippet?: string;
	highlights?: string[];
	metadata?: Record<string, unknown>;
}

export type Page = 'discover' | 'analyze' | 'organize' | 'settings';
